version: '3.7'

services:
  app:
    image: nginx:1.16.1
    ports:
      - "8888:80"
    volumes:
      - ./conf/app/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
  phpfpm:
    build: './dockerfile/phpfpm'
    container_name: m2ee_php
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    container_name: m2ee_mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: m2ee_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: m2ee_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9654:80

  elasticsearch:
    image: elasticsearch:7.7.1
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      discovery.type: single-node