version: '3.7'

services:
  app:
    image: nginx:1.16.1
    ports:
      - "8888:80"
    volumes:
      - ./conf/app/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
  phpfpm:
    build: './dockerfile/phpfpm'
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  elasticsearch:
    image: elasticsearch:7.7.1
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      discovery.type: single-node